// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPt7D6z7rjlZNvFPzjZXUVhlo1ezXdmg',
    appId: '1:1048536605397:web:ed1b0d7b3ca4532442385c',
    messagingSenderId: '1048536605397',
    projectId: 'fateen-5208e',
    authDomain: 'fateen-5208e.firebaseapp.com',
    storageBucket: 'fateen-5208e.firebasestorage.app',
    measurementId: 'G-Y308JEQVR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA86NGu3pk3pET5vZqbnYywx-XgMJTtLa4',
    appId: '1:1048536605397:android:87d19652b27a6d7442385c',
    messagingSenderId: '1048536605397',
    projectId: 'fateen-5208e',
    storageBucket: 'fateen-5208e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ53Bk1ZGYl0MGBib9Pf8AIHGd_IQSfzo',
    appId: '1:1048536605397:ios:fa3eec8c6f90556442385c',
    messagingSenderId: '1048536605397',
    projectId: 'fateen-5208e',
    storageBucket: 'fateen-5208e.firebasestorage.app',
    iosBundleId: 'com.examfple.fateen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ53Bk1ZGYl0MGBib9Pf8AIHGd_IQSfzo',
    appId: '1:1048536605397:ios:c424b3d7d609126242385c',
    messagingSenderId: '1048536605397',
    projectId: 'fateen-5208e',
    storageBucket: 'fateen-5208e.firebasestorage.app',
    iosBundleId: 'com.example.fateen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMPt7D6z7rjlZNvFPzjZXUVhlo1ezXdmg',
    appId: '1:1048536605397:web:0fa9da9253de236442385c',
    messagingSenderId: '1048536605397',
    projectId: 'fateen-5208e',
    authDomain: 'fateen-5208e.firebaseapp.com',
    storageBucket: 'fateen-5208e.firebasestorage.app',
    measurementId: 'G-NGNCCG7KXS',
  );
}
